# Generated by Django 3.2.8 on 2021-10-09 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('slug', models.SlugField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('user_image', models.FileField(upload_to='images/user_cus/')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinefood.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Socialmedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(blank=True, max_length=10, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('restaurant_phone_number', models.PositiveIntegerField()),
                ('restaurant_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('opening_status', models.IntegerField(choices=[(1, 'open'), (2, 'closed')], default=1)),
                ('email', models.EmailField(max_length=254)),
                ('restaurant_website', models.TextField()),
                ('lit', models.CharField(max_length=200)),
                ('long', models.CharField(max_length=200)),
                ('trade_lic_image', models.FileField(upload_to='images/trade_lic/')),
                ('lic_validation_date', models.DateTimeField(blank=True, null=True)),
                ('res_validation_date', models.DateTimeField(blank=True, null=True)),
                ('features', models.IntegerField(choices=[(1, 'breakfast'), (2, 'launch'), (3, 'dinner'), (4, 'delivery'), (5, 'cafe'), (6, 'luxury dining'), (7, 'night life')], default=3)),
                ('timings', models.IntegerField(choices=[(1, 'monday'), (2, 'tuesday'), (3, 'wednesday'), (4, 'thursday'), (5, 'friday'), (6, 'saturday'), (7, 'sunday')], default=1)),
                ('opening_from', models.TimeField()),
                ('opening_to', models.TimeField()),
                ('other_details', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinefood.socialmedia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinefood.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinefood.menu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinefood.order')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinefood.restaurant'),
        ),
        migrations.CreateModel(
            name='Marchent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('no_of_restaurant', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=20)),
                ('telephone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
                ('mar_image', models.FileField(upload_to='images/mar_image/')),
                ('nid_driving_lic_image', models.FileField(upload_to='images/nid/')),
                ('res_date', models.DateTimeField(auto_now_add=True)),
                ('validation_date', models.DateTimeField(blank=True, null=True)),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinefood.socialmedia')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinefood.socialmedia'),
        ),
    ]
