# Generated by Django 3.2.8 on 2021-10-10 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefood', '0003_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order_tracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinefood.customer')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinefood.order')),
                ('track_Delivery_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinefood.deliveryagent')),
            ],
        ),
    ]
