# Generated by Django 3.2.8 on 2021-10-10 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefood', '0005_auto_20211010_2340'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='restaurantreview',
            unique_together=set(),
        ),
    ]
